### ISSUE TITLE
Error on Debian Jessie trying to run 1.2.1 

### ISSUE THREAD

**Issue by opentokix** [Exa-Networks/exaproxy#37] opened 2015-09-01 07:51 UTC
```
--------------------------------------------------------------------------------
-- Please provide the information below on :
-- http://code.google.com/p/exaproxy/issues/entry
--------------------------------------------------------------------------------


-- Version

2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]


-- Logging History


Tue, 01 Sep 2015 09:48:58 supervisor error         Starting exaproxy version 1.2.1
Tue, 01 Sep 2015 09:48:58 supervisor error         python version 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2]
Tue, 01 Sep 2015 09:48:58 supervisor debug         starting /root/dl/exaproxy-1.2.1/lib/exaproxy/application.py
Tue, 01 Sep 2015 09:48:58 daemon info          for information, your configuration requires 65826 available file descriptors
Tue, 01 Sep 2015 09:48:58 supervisor info          the chosen polling reactor was epoll
Tue, 01 Sep 2015 09:48:58 server info          server [http proxy] accepting up to 32768 clients
Tue, 01 Sep 2015 09:48:58 server info          server [web server] accepting up to 100 clients
Tue, 01 Sep 2015 09:48:58 server info          server [icap server] accepting up to 32768 clients


-- Traceback


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/util/debug.py", line 71, in <module>
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/application.py", line 306, in <module>
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/application.py", line 276, in main
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/supervisor.py", line 131, in __init__
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/supervisor.py", line 211, in interfaces
  File "/root/dl/exaproxy-1.2.1/lib/exaproxy/util/interfaces.py", line 233, in getifaddrs
TypeError: integer expected


--------------------------------------------------------------------------------
-- Please provide the information above on :
-- http://code.google.com/p/exaproxy/issues/entry
--------------------------------------------------------------------------------


ExaProxy 18024  supervisor    Starting exaproxy version 1.2.1
ExaProxy 18024  supervisor    python version 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2]
ExaProxy 18024  worker 1      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 2      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 3      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 4      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 5      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 6      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 7      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 8      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 9      could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
ExaProxy 18024  worker 10     could not spawn process /root/dl/exaproxy-1.2.1/etc/exaproxy/redirector/url-allow
```

**Comment by thomas-mangin** [comment] 2015-09-05 18:08
Sorry for the delay in replying, what OS are you running ExaProxy on ? It seems we are having issue with the code which tried to extract the IP addresses on the interfaces, so could you please provide us an output of 'ip addr show' / 'netstat -in'

**Comment by thomas-mangin** [comment] 2015-09-05 18:10
It seems to be a duplicate of #35 - which I believe had been fixed.

**Comment by thomas-mangin** [comment] 2016-07-23 17:29
no reply - closing.

**Closed by thomas-mangin** 2016-07-23 17:29 UTC
Labels: bug
